version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - curl https://$GITHUB_TOKEN@raw.githubusercontent.com/potatowagon/spring-application-properties/master/oppenheimer/application.properties -o ./src/main/resources/application.properties
      - mvn clean
      - mvn install
artifacts:
  files:
    - 'target/demo-0.0.1-SNAPSHOT.jar'